import { test, expect } from "@playwright/test";
import { installApi, ids, order, transaction } from "../helpers/api.js";
test("admin reviews and rejects requests with an explicit server reason", async ({ page }) => {
  const state = await installApi(page, { role: "ADMIN", orders: [order()] });
  await page.goto("/sistema/pedidos");
  await page.getByRole("button", { name: /Abrir pedido AR-/ }).click();
  await page.getByRole("button", { name: "Marcar em análise" }).click();
  await expect(page.getByRole("dialog").getByText("Em análise", { exact: true }).first()).toBeVisible();
  await page.getByRole("button", { name: "Recusar", exact: true }).click();
  await page.getByLabel("Motivo da recusa").fill("Modelo indisponível para a data.");
  await page.getByRole("button", { name: "Confirmar recusa" }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  expect(state.orders[0].status).toBe("REJECTED");
  expect(state.orders[0].rejectionReason).toBe("Modelo indisponível para a data.");
});
test("direct sale uses registered customer, variant UUID and integer cents", async ({ page }) => {
  const state = await installApi(page, { role: "ADMIN" });
  await page.goto("/sistema/locacoes");
  await page.getByRole("button", { name: "Nova operação" }).click();
  await page.getByRole("combobox", { name: "Modalidade", exact: true }).selectOption("SALE");
  await page.getByLabel("Cliente cadastrado").selectOption(ids.client);
  await page.getByRole("combobox", { name: "Modelo", exact: true }).selectOption(ids.product);
  await page.getByRole("combobox", { name: "Tamanho", exact: true }).selectOption(ids.variant);
  await page.getByLabel("Valor em reais").fill("950.25");
  await page.getByRole("button", { name: "Salvar rascunho" }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  expect(state.requests.find(r => r.path === "/transactions" && r.method === "POST").body).toEqual({ variantId: ids.variant, profileId: ids.client, type: "SALE", priceCents: 95025 });
  await page.getByRole("button", { name: "Confirmar operação" }).click();
  await page.getByRole("button", { name: "Registrar entrega" }).click();
  await expect(page.getByText("Concluído", { exact: true })).toBeVisible();
});
test("editing and cancelling a draft use supported transaction endpoints", async ({ page }) => {
  const state = await installApi(page, { role: "ADMIN", transactions: [transaction({ type: "SALE", startDate: null, endDate: null })] });
  await page.goto("/sistema/locacoes");
  await page.getByRole("button", { name: "Editar rascunho" }).click();
  await page.getByLabel("Valor em reais").fill("1000.01");
  await page.getByRole("button", { name: "Salvar rascunho" }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  expect(state.requests.find(r => r.method === "PATCH" && r.path.startsWith("/transactions/")).body.priceCents).toBe(100001);
  page.once("dialog", dialog => dialog.accept());
  await page.getByRole("button", { name: "Cancelar operação" }).click();
  await expect(page.getByText("Cancelado", { exact: true })).toBeVisible();
});
test("the returns page reads API transactions and does not mount the old tailoring board", async ({ page }) => {
  await installApi(page, { role: "ADMIN", transactions: [transaction({ status: "CONFIRMED", pickedUpAt: "2026-10-15T12:00:00Z" })] });
  await page.goto("/sistema/ajustes");
  await expect(page.getByText(/O acompanhamento de costura ainda não está disponível/)).toBeVisible();
  await expect(page.getByRole("button", { name: "Registrar devolução" })).toBeVisible();
  await expect(page.locator(".atelier-board")).toHaveCount(0);
});
